### ISSUE TITLE
Assignment of IK-JL keys for navigation.

### ISSUE THREAD

**Issue by pawelurbanski** [javidominguez/easyNavigation#3]
I modified the script to assign IK-KL keys to use for navigation.
The very handy feature of such feature is that it is not required to move the hand of the home-row on the keyboard.
Unfortunately the add-on throws errors and does not work consistantly. It may be related to the fact that some of the keys used for navigation without the add-on are used in that case for: lists, list items and links.
A very wlecome feature would be the ability to select a navigation key and pick the script to be executed.
For example: Assigning "Read all" in place of the reading non-links block of text under the "N" key would make much more sense. Currently, NVDA reads just a single line and one needs to either press NVDA+DownArrow or keep scrolling line-by-line.
Will be happy to help with a bit of code, but it might be a good idea to discuss this first.

**Comment by javidominguez** [comment]
Adding a new set of keys is as simple as including it in the dictionary navKeysModes.

Almost always some navigation key will overlap an existing script that is why the addon manages the gesture bindings in a way that avoids most conflicts, but it could happen that another script loaded later, perhaps by another addon, takes preference over a gesture.

I don't know what exactly you mean by a feature to ability to select a navigation key and pick the script to be executed. Do you want to say something like remap the quick navigation keys? I think that would be complicated and out of the scope of this addon.
